Add auth endpoint
junichi-fukushima/tech-flow pull request #75
Opened 2024-11-18 22:15 UTC by kei0405

## 概要

- https://github.com/junichi-fukushima/tech-flow/issues/xx

## 概要

## 詳細

## 関連資料

2024-11-18 23:44 UTC, junichi-fukushima commented
@kei0405 
PRへのissueのチケット添付はmustでお願いしたいです🙏

2024-11-18 23:48 UTC, junichi-fukushima requested changes
一旦途中まで今日明日で続き見ます。

2024-11-18 23:48 UTC, junichi-fukushima commented on backend/handlers/auth/main.go
> +		log.Fatalf("failed init auth repo")
こちらのloggerを使っていただけると🙏
https://github.com/junichi-fukushima/tech-flow/blob/c0af85a1b372f62552a7ae67999d582201524e9d/backend/infrastructure/external/log/logger.go#L9

2024-11-20 12:55 UTC, y-tsubuku approved these changes
loggerの部分以外、LGTMです 🎉

2024-11-20 12:55 UTC, y-tsubuku commented on backend/infrastructure/repository/auth_repository.go
> +	return nil
IMO: 自分なら一発でreturnしちゃうかもです 📝 
```suggestion
	return repo.db.DB.Create(&user).Error
```

2024-11-22 00:55 UTC, kei0405 commented on backend/handlers/auth/main.go
> +		log.Fatalf("failed init auth repo")
対応しました！

2024-11-22 01:36 UTC, y-tsubuku approved these changes
追加変更点含めてLGTMです 🎉

2024-11-22 22:15 UTC, merged