ドラフト
junichi-fukushima/tech-flow pull request #76
Opened 2024-11-19 01:50 UTC by jun-koyama-h

## 概要

- https://github.com/junichi-fukushima/tech-flow/issues/xx

## 概要

## 詳細

## 関連資料

2024-11-19 10:35 UTC, junichi-fukushima commented on backend/usecase/article_usecase.go
> +		log.Fatalf("Failed to get articles: %v", err)
こちらのloggerを使っていただけると🙏
https://github.com/junichi-fukushima/tech-flow/blob/c0af85a1b372f62552a7ae67999d582201524e9d/backend/infrastructure/external/log/logger.go#L9

2024-11-19 10:36 UTC, junichi-fukushima requested changes
ここら辺使っていただけるとmm

https://github.com/junichi-fukushima/tech-flow/blob/main/backend/infrastructure/external/http/http_handler.go

2024-11-19 11:56 UTC, junichi-fukushima commented on backend/handlers/articles/main.go
> +var uc usecase.ArticleUsecase
var定義せずhandler関数内で🙏

2024-11-22 06:11 UTC, jun-koyama-h commented on backend/handlers/articles/main.go
> +var uc usecase.ArticleUsecase
グローバル変数にして、initで初期化のがよさげなのでこのままにしてます。

2024-11-22 06:14 UTC, jun-koyama-h commented on backend/usecase/article_usecase.go
> +		log.Fatalf("Failed to get articles: %v", err)
loggerに修正しました ☺️

2024-11-22 08:02 UTC, kei0405 commented on backend/infrastructure/repository/article_repositoy.go
> +}
記事を取得する場合はデフォルト `created_at` or `updated_at` が最新の方がいいんですかね？今だと、インクリメンタルなID順？

2024-11-22 08:40 UTC, jun-koyama-h commented on backend/handlers/articles/main.go
> +	validator := validator.New()
init()に移動しました ♻️

2024-11-22 08:40 UTC, jun-koyama-h commented on backend/handlers/articles/main.go
> +	req.SetDefaults()
移動しました ♻️

2024-11-22 08:40 UTC, jun-koyama-h commented on backend/usecase/article_usecase.go
> +	var articlesDTO []dto.Article
修正しました。 ♻️

2024-11-22 08:41 UTC, jun-koyama-h commented on backend/usecase/article_usecase.go
> +		articlesDTO = append(articlesDTO, convertArticleToDTOArticle(article))
修正しました。 ♻️

2024-11-22 08:41 UTC, jun-koyama-h commented on backend/dto/article.go
> +	Offset   int64  `json:"offset" validate:"min=0"`
intに変更しました。 ♻️

2024-11-22 08:42 UTC, jun-koyama-h commented on backend/infrastructure/repository/article_repositoy.go
> +}
一旦、created_atにしました。

2024-11-22 12:13 UTC, y-tsubuku reviewed
Goを初めて数週間と思えないPRに震えました。流石です！

2024-11-22 12:13 UTC, y-tsubuku commented on backend/infrastructure/repository/article_repositoy.go
> +		Preload("Tags").
Preload いいですね～！

2024-11-22 12:13 UTC, y-tsubuku commented on backend/infrastructure/repository/article_repositoy.go
> +	var domainArticles []article.Article
他のところもそうですが、ここはメモリ効率を考えるとこうした方が良かったような記憶があります。capを超えると毎回アロケートされるような物があった記憶があります。
```suggestion
	domainArticles := make([]article.Article, 0, len(articles))
```
mustではないです！ぶっちゃけ、あまり問題にならないレベルだと思います

2024-11-22 12:13 UTC, y-tsubuku commented on backend/usecase/article_usecase.go
> +		initializer.Logger.Error("Failed to get articles.", "error", err)
ここは return しないと後続の処理が行われてしまいそうです！
```suggestion
		initializer.Logger.Error("Failed to get articles.", "error", err)
		return err
```

2024-11-22 12:13 UTC, y-tsubuku commented on backend/usecase/article_usecase.go
> +		ImageURL:    "", // TODO 画像URLの取得方法を検討
これはOGPを別で取りますかねー。CORSを気にしなければフロントで取っちゃうのもなくないですね。

2024-11-23 00:10 UTC, merged